# Integracion de las funcionalidades con development

name: Integracion de feature en development
on:
  push:
    branches: [HU*]
jobs:
  back:
    name: Pruebas backend
    runs-on: ubuntu-latest
    steps:
    - name: Checkout del repositorio
      uses: actions/checkout@v2
    - name: Configuracion de entorno Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Instalacion de librerias y dependencias
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Ecutar pruebas unitarias
      id: correr-pruebas
      run: |
        python -m unittest discover tests/
    - name: Validar resultado con errores
      if: ${{ failure() }}
      env:
        MENSAJE_ERROR: Una o varias pruebas fallaron
      run: echo "::set-output name=respuesta::${MENSAJE_ERROR}"
    - name: Validar resultado sin errores
      if: ${{ success() }}
      env:
        MENSAJE_EXITO: Todas las pruebas fueron exitosas
      run: echo "::set-output name=respuesta::${MENSAJE_EXITO}" 
  merge-branch:
    name: Automerge
    needs: back
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Merge rama actual -> development
        uses: devmasx/merge-branch@v1.3.1
        with:
          type: now
          target_branch: dev
          github_token: ${{ github.token }}
